---
title: "ShotSpotter Update"
output: 
  pdf_document:
    number_sections: true
    extra_dependencies: ["float"]
author: 
  - Michael Topper and Toshio Ferrazares
date: "Last Updated: `r Sys.Date()`"
citation_package: natbib
editor_options: 
  chunk_output_type: console
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage{bbm}
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage{indentfirst}
- \usepackage[fontsize=12pt]{scrextend}
- \usepackage{graphicx}
- \usepackage[utf8]{inputenc}
- \usepackage{pdfpages}
- \usepackage[round,authoryear]{natbib}
- \usepackage{setspace}\onehalfspacing
- \usepackage{subfig}
- \usepackage{placeins}
- \usepackage{rotating}
- \usepackage{fancyhdr}
- \usepackage{times}
- \usepackage{endnotes}
- \floatplacement{figure}{H}
linkcolor: blue
link-citations: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
library(fixest)
library(modelsummary)

knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.align = "center",fig.pos = "H", out.extra = "")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Trying to figure out new directions. We have somewhat solidified a good set of results and think they are relatively robust.


\newpage
\FloatBarrier

# Figures

```{r}
source("figures/rollout_date_figure.R")
```


```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
rollout_figure
```
```{=latex}
\caption{ShotSpotter Rollout Dates by District in Chicago \label{rollout_figure}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. 
\end{figure}
```

```{r}
source("figures/shotspotter_alert_trends.R")
```

```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
shotspotter_trend
```
```{=latex}
\caption{ShotSpotter Alerts Over Time \label{shotspotter_trend}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows the trend of the number of gunshots alerted by ShotSpotter.
\end{figure}
```

```{r}
source("figures/event_study_dispatches.R")
```


```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
entry_1_es
```
```{=latex}
\caption{Event Study of Priority 1 Dispatch Times \label{entry_1_es}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows priority 1 time from received 911 call to time of dispatch. Priority 1 calls are designated as immediate dispatch.
\end{figure}
```




```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
entry_2_es
```
```{=latex}
\caption{Event Study of Priority 2 Dispatch Times \label{entry_2_es}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows priority 2 time from received 911 call to time of dispatch. Priority 2 calls are designated as rapid dispatch.
\end{figure}
```


```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
entry_3_es
```
```{=latex}
\caption{Event Study of Priority 1 Dispatch Times \label{entry_1_es}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows priority 3 time from received 911 call to time of dispatch. Priority 3 calls are designated as routine dispatch.
\end{figure}
```


```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
os_1_es
```
```{=latex}
\caption{Event Study of Priority 1 Dispatch to On-Scene Times \label{os_1_es}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows priority 1 time from a dispatched 911 call to the time the officer gets on-scene. Priority 1 calls are designated as immediate dispatch.
\end{figure}
```



```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
os_2_es
```
```{=latex}
\caption{Event Study of Priority 2 Dispatch to On-Scene Times \label{os_2_es}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows priority 2 time from a dispatched 911 call to the time the officer gets on-scene. Priority 2 calls are designated as rapid dispatch.
\end{figure}
```



```{=latex}
\begin{figure}[t!]
```
```{r, fig.align='center'}
os_3_es
```
```{=latex}
\caption{Event Study of Priority 3 Dispatch to On-Scene Times \label{os_3_es}}
\textit{Note:} There are a total of 18 police districts in Chicago, 12 of which get ShotSpotter implemented. Implementation began in early 2017 through late 2018. This graph shows priority 3 time from a dispatched 911 call to the time the officer gets on-scene. Priority 3 calls are designated as routine dispatch.
\end{figure}
```
\newpage
\FloatBarrier
# Tables


```{r}
source("tables/regressions_dispatches.R")
```


```{r}
dispatch_table %>% 
  landscape()
```