---
title: "Untitled"
output: pdf_document
date: "2023-08-01"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

# Sensitivity Analysis of Event Study

In this appendix, we conduct analysis following Roth (2022) to illustrate the sensitivity of our causal inferences on the event study estimates in Figures \ref{} and \ref{}. Specifically, we evaluate the degree of nonlinearity we can impose on a linear extrapolation of the pre-treatment trend. We adopt the notation used in ROTH and define $M$ as the amount that the pre-treatment trend can change across consecutive periods. As an example, $M =0$ implies that the counterfactual difference in trends is exactly linear. Conversely, as $M$ increases ($M >0$), we allow for more nonlinearity in the pre-treatment trend and therefore greater uncertainty in the treatment effect estimates. Therefore, estimates that remain significant under larger values of $M$ are more robust to different extrapolations of pretrends. 



We construct robust confidence intervals and benchmark our "breakdown" value of $\bar{M}$  