---
title: "Background"
output: pdf_document
date: "2023-06-19"
---


\section{Background}\label{section:background}
 

\subsection{ShotSpotter Technology and Implementation in Chicago}\label{section:sstchicago}

ShotSpotter is an acoustic gunfire technology that employs a network of microphones and sensors on buildings and light-posts to detect gunfire sounds.
These sounds are used to triangulate the location of potential gunfire, which is then relayed to nearby police officers.
Over the past decade, this technology has seen significant expansion and is now operational in over 150 cities globally.
Advocates promote the technology as a tool for enabling rapid police response to gunfire incidents, whereby they can catch the perpetrators, and reduce the quantity of guns. Moreover, the unique functionality of ShotSpotter allows police departments to bypass their reliance on civilian reporting. However, previous studies have found mixed evidence supporting these claims (this needs a BIG cite here). 

The technology relies on machine learning algorithms to classify sounds of potential gunfire.\footnote{According to ShotSpotter's website, from 2019 to 2021, the aggregate accuracy rate across all of their customers was 97 with a very small false-positive rate of approximately 0.5\%, however this has not been independently tested.} When a potential gunshot is detected, the sensors triangulate the location of the noise and data/recordings on the incident are forwarded to ShotSpotter's Incident Review Center. At this center, a human reviewer assesses the data, and flags for false-positives to avoid erroneous alerts. Once a gunshot is confirmed, information regarding the location and number of shots fired are shared with the police department where dispatchers can then send officers to scene. This entire process from gunshot noise to police dispatch is known as a \emph{ShotSpotter dispatch}.

In Chicago, ShotSpotter technology has been implemented in 12 of the 22 police districts. The staggered roll-out begins in January 2017 and ends in May 2018.\footnote{This wide-scale adoption follows previous testing of select areas between 2003 and 2007, and again in 2012. However, no district received district-wide coverage during this trial period and the extent of testing was small (https://www.cbsnews.com/chicago/news/chicago-police-testing-new-gunshot-detection-technology/), Office of Inspector General} Officially, there is no justification for the specific order in which certain police districts are chosen to receive ShotSpotter. Nevertheless, it is important to note that the police districts chosen have historically high rates of gun violence.\footnote{Note that difference-in-differences relies on the assumption of common trends, not random assignment of the rollout.}Appendix Figure \ref{map} shows the locations of the 12 police districts in Chicago that received ShotSpotter technology. As mentioned previously, the areas where this technology is implemented (the South and West Chicago areas) experience higher rates of gun crime on average.


\subsection{Dispatching 911 Calls and ShotSpotter Alerts in Chicago}\label{section:dispatchingchicago}

In Chicago, the coordination of emergency 911 calls involves two main entities: the Office of Emergency Management (OMEC) and the Chicago Police Department (CPD). The OEMC oversees 911 calls and dispatches available police officers to the crime scenes. Each 911 call is prioritized on a scale of imminent danger/threat ranging from Priority 1 (immediate dispatch) to 3 (routine dispatch).\footnote{Technically, there are 6 priorities ranging from priority 0-5. However, Priority 0, 4, and 5 are reserved for special cases such as police officers calling for emergency assistance, administrative meetings, or alternate responses that do not need a field unit respectively.}

On the other hand, the coordination of ShotSpotter dispatches is a collaborative effort involving the OEMC, CPD, and the Strategic Decision Support Center (SDSC). When gunfire is detected, ShotSpotter's headquarters sends vital information such as the location, time, severity, amount of shots being fired, and direction of possible offender to the SDSC. The SDSC then synthesizes this information and notifies the OEMC to immediately dispatch a police officer to the location of the gunfire.

Importantly, each ShotSpotter alert is classified with the same distinction as a Priority 1 911 call. Priority 1 necessitates immediate dispatch due to the imminent threat to life, bodily injury, or major property damage/loss. Hence, both Priority 1 911 calls and ShotSpotter alerts share the same dispatch procedures and responding officers. Furthermore, the OEMC prioritizes dispatching all Priority 1 emergencies to rapid response units and police officers within the police district of occurrence.\footnote{Specifically, dispatchers prioritize dispatching police officers within the beat they are assigned to. Police beats are subsections within police districts.} Only in rare circumstances are police officers assigned to emergencies outside their district.\footnote{In particular, the dispatching order is in the following order of priority: rapid response unit or beat unit from the beat of occurrence, tactical unit, rapid response sergeant, sector sergeant, tactical sergeant, other field supervisor, and closest available unit.}

Despite the similarities in ShotSpotter dispatches and Priority 1 911 calls, police officers must follow an additional operating procedure when arriving to the location of a ShotSpotter alert. In particular, officers are instructed to canvass a 25-meter radius of the precise location identified via the ShotSpotter system for victims, evidence, and witnesses. Moreover, officers are also expected to notify the SDSC if they are aware of any deficiencies in ShotSpotter data or alerts, and if completing a case report, to document if the case incident is ShotSpotter-related. According to the data on ShotSpotter-related dispatches, each ShotSpotter dispatch takes an officer an average of 20 minutes to complete the investigation once they have arrived on-scene. 
