---
title: "Data"
output: pdf_document
date: "2023-06-19"
---



\section{Data}\label{section:data}

\subsection{Data Sources}\label{section:datasources}

The main sample is a daily-level panel from 2016 to 2022 that is constructed using several administrative data sets obtained through Freedom of Information Act requests to the Chicago Police Department (CPD).
This data contains 911 call dispatches, officer shifts of sworn police officers, and district-level ShotSpotter activation dates.
Additionally, these data are supplemented with reported incidents of crime, arrests, and ShotSpotter dispatches downloaded from Chicago's Open Data Portal. 

The CPD 911 call dispatch data encompasses all 911 calls that led to the dispatch of a CPD officer. This administrative data is rich, containing information on the time of the 911 call, the time an officer is dispatched to the scene of the crime, and the time the officer arrives on-scene, each recorded at the seconds level. Additionally, the data details details the priority-level of the call, a brief description, a location, and an indication of if an arrest is made.

Based on this information, we construct the two main outcome variables: the time from a 911 call to an officer dispatch (call-to-dispatch) and the the time from a 911 call to an officer's arrival (call-to-on-scene). Notably, while call-to-dispatch contains no missing data, approximately 52\% of the call-to-on-scene information is missing due to officers failing to report when they arrive at the scene. However, we address this potential limitation in Appendix Table BLANK where we find little evidence of significant changes in the frequency of officers failing to report their on-scene time due to ShotSpotter's rollout.

These two measures of time accomplish different measures of police availability.
If an officer is busy, they will be delayed or unable to be dispatched.
This increase in time would be seen as a higher call-to-dispatch time and is a function of the coordination of a OEMC dispatcher and an individual police officer.
On the other hand, call-to-on-scene, which captures both the dispatch time and the time an officer takes to arrive on scene may increase independently of call-to-dispatch time if, for example, an officer drives at a slower speed or is located farther away from their dispatch location.

The police shift data contains information on every shift start time, end time, and district/beat assignment worked by CPD staff in the sample period. We restrict the shift data to include only police officers that are present for duty, excluding administrative positions and higher level managerial roles such as police lieutenants and police chiefs. To assess officer availability, we construct the number of officer hours within a police district-day. By using on the number of officer hours rather than the number of shifts, we account for the possibility of overtime or early-leave.

The ShotSpotter activation dates indicate when each police district is equipped with ShotSpotter technology. However, since the exact day is missing, we rely on ShotSpotter alert data, which provides minute-level alerts. This allows us to determine the specific activation day for each police district. Nonetheless, we observe several discrepancies in the activation dates when comparing to the number of alerts in districts 6, 9, 10, and 15. In particular, these districts have no ShotSpotter alerts until several months after their official activation date. Therefore, we adjust these four dates of activation to align with the onset of ShotSpotter alerts. This adjustment ensures that the effects observed are accurately attributed to police officers responding to ShotSpotter alerts. However, as a robustness check, we estimate the results using the official dates in Appendix Figure \ref{forest_sample_plot} and find that the results remain consistent.

Figure \ref{shotspotter_trend} shows the monthly trend of ShotSpotter dispatches in addition to the activation dates as displayed by the dashed line. Each police district exhibits an increase in ShotSpotter dispatches as time progresses. This is possibly due to ShotSpotter's machine learning algorithms refining with time. 

\subsection{Sample Restrictions}\label{section:samplerestrictions}

We restrict the sample to only 911 call dispatches of Priority 1 (immediate dispatch), Priority 2 (rapid dispatch), and Priority 3 (routine dispatch).\footnote{We also include Priority 0 (Emergency Assistance), since these are time-sensitive responses. However, these are extremely rare and occur in less than 0.1\% of the sample.} Priorities 4 and 5 are omitted as these are reserved for special cases and administrative designations such as a police beat-meeting. These exclusions account for approximately ~0.04\% of the total number of 911 dispatches. By including only Priority 1-3 the analysis focuses only on the call types that are most commonplace or require the most time-sensitive responses. 

Three further restrictions are implemented to reduce sensitivity of the estimates. First, all observations that exhibit a negative call-to-dispatch or call-to-on-scene time are removed, accounting for approximately 0.03\% of the data. Second, for each priority level, call-to-dispatch and call-to-on-scene outliers that exceed three standard deviations from the mean are omitted. This is done to mitigate the impact of outliers on the ordinary least squares estimator which is sensitive to extreme values. We relax this restriction in Appendix Figure BLANK to verify the consistency of the results. Last, specific dates including January 1, July 4, and December 31 are excluded from the analysis. These dates coincide with celebratory gunfire and fireworks that may generate many false-positive ShotSpotter alerts. 

\subsection{Descriptive Statistics} \label{section:summarystats}

Each data source is aggregated to the police district-day and matched by police district and date. Importantly, both call-to-dispatch and call-to-on-scene times are averaged, and hence, these outcomes are interpreted as average daily response times within a police district-day. Conversely, officer hours, ShotSpotter dispatches, crimes and arrests are aggregated as counts and therefore represent the number of occurrences within a police district-day.

Table \ref{summary_stats} shows summary statistics of the main outcome variables and corresponding control variables, all presented at the police district-day level. Panel A shows that the time to dispatch a police officer to the crime scene for Priority 1 911 calls (Call-to-Dispatch) is approximately four minutes, while it takes police officers an additional six minutes on average to arrive on-scene. We additionally plot the distribution of both of these outcome variables in Figure \ref{distribution_outcomes} which shows that the average daily call-to-dispatch and call-to-on-scene times are centered around their mean, although their right tails are rather large. Priority 1 calls are the most frequent as shown in Panel B, and police officers are dispatched approximately 150 times a day within a district. Moreover, for every 100 police dispatches, there are approximately 14 arrests made (Arrest Rate). Considering the high level of crime in the South and West locations of Chicago, the presence of officers varies considerably across districts, ranging from as little as 200 officer-hours or as high as 3431 officer-hours. We later analyze this heterogeneity in officer hours in Section \ref{section:mainresults} where we find longer response times when there are fewer officers. 
