---
title: "Heterogeneity"
output: pdf_document
date: ""
---
\section{Heterogeneity}\label{section:hetereogeneity}

\subsection{Is ShotSpotter most hindering in resource-constrained times?}\label{section:resourceconstrain}

In this subsection, we further test the notion that instances of limited officer resources are more prone to experiencing the higher workloads resulting from ShotSpotter implementation. As alluded to in Columns 5 and 6 of Table \ref{main_results}, ShotSpotter has a larger effect on response times when there are fewer officers.
Remarkably, days with fewer officers working exhibit treatment effects up to three times as more than those with more officers on duty. We supplement this prior analysis by considering days and times where there are higher officer workloads. To do this, we split the sample by the median number of 911 dispatches in a district-day and by different officer shift schedules. In doing so, we isolate times where officers have higher workloads, and are therefore more likely to be delayed by ShotSpotter dispatches.

Figure \ref{hetero_resource} shows the results from these two analyses. In the left column, days are separated by the number of 911 dispatches per day.
Days with a large number of dispatches represent days with higher crime levels.
These high crime days show evidence of a larger increase in both Call-to-Dispatch time and Call-to-On-Scene time.
Next, in the right column, dispatches are split based on the time of day that they occur, using the 3 Watches that officers work.
Similarly, Watch 3 that operates during the evening, and which faces the highest levels of crime, see the largest treatment effect of each of the three watches.


NOTE TO HEATHER/KEVIN: we feel like this is kind of weak evidence, but it fits in with our story.




\subsection{How does ShotSpotter affect other priority response times?}\label{section:priorities}

If ShotSpotter is affecting response times by depleting police resources, then 911 calls with less urgency may be relatively less affected. 
Recall from Section \ref{section:data} that there are three main 911 call priorities: Priority 1 (immediate dispatch), Priority 2 (rapid dispatch), and Priority 3 (routine dispatch). Priorities 1 and 2 are both time-sensitive call types in which timely police response may affect the outcome of the incident. On the other hand, Priority 3 does not require rapid response.

In Figures \ref{priorities_dispatch} and \ref{priorities_onscene} Equation \ref{eq:main} is estimated on response times by priority. Next, each priority is separated by the five most frequent call types.
For each call type, the percent change from the mean in addition to the 95\% confidence interval is plotted while the number of observations (N) and corresponding point estimate (Estimate) are shown on the y-axis. As such, each  separate regression where the outcome is either Call-to-Dispatch or Call-to-On-Scene time. 

Nearly all Priority 1 and Priority 2 calls exhibit increases in both Call-to-Dispatch and Call-to-On-Scene times while Priority 3 calls show no statistically significant effect. These results align with the notion that ShotSpotter affects time-sensitive calls while having little discernible impact on calls of lesser time-sensitivity, as seen in Priority 3. However, it is worth noting that Priority 3 calls are investigated when police officers have available time. Interestingly, positive point estimates are reported across the top 5 Priority 3 calls, thereby suggesting that officers may have less availability when ShotSpotter is implemented.
