---
title: "Introduction"
output: pdf_document
date: ""
---


\section{Introduction}

Artificial intelligence (AI) has surpassed its role in social media consumption, becoming an integral component of modern policing. As of 2023, police departments are utilizing AI policing technologies such facial recognition, traffic cameras, and predictive algorithms in effort to combat rising violent crime. These AI technologies are seen as imperative to public safety moving forward, in effort to mitigate both police officer shortages and all-time high levels of public mistrust in police.

One quickly expanding and widely adopted AI technology is ShotSpotter—an acoustic gunfire detection technology which is currently implemented in over 150 cities world-wide. Shotspotter's primary intention is to rapidly dispatch police officers to violent crime scenes to catch perpetrators and reduce gun violence. The technology utilizes an array of microphones and sensors placed on street lights and buildings that use machine learning algorithms to detect the sound of gunfire, triangulate its location, and alert police officers for rapid response. Because of its unique functionality, ShotSpotter bypasses the reliance on civilian reporting which has been facing a persistent decline since 2020 \citep{ang_police_2021}. In effect, previous studies have utilized this feature of ShotSpotter as a measure of underlying crime that is independent of reporting \citep{carr_geography_2016,carr_keep_2018, ang_police_2021}.

Despite ShotSpotter's prevalence, there is little consensus on its intended effect on gun violence, or more insidiously, its unintended consequences on policing given the extensive amount of police resources it requires. In Chicago, the setting of this paper, nearly all instances of gunfire detected by ShotSpotter result in a police unit dispatching to the potential crime scene. Each of these detections are designated as Priority 1 (immediate dispatch)—the equivalent priority to a report of an active shooter. As a result, an average day in Chicago experiences approximately 60 ShotSpotter dispatches with officers spending roughly 20 minutes investigating the crime scene. This large allocation equates to 20 hours of daily officer resources and comes at the cost of another time-sensitive police responsibility—Priority 1 911 call response times. 

In this paper, we utilize variation in timing from ShotSpotter rollout-outs across Chicago police districts from 2016-2022 to estimate the causal effect of ShotSpotter technology on response times from 911 calls designated as Priority 1. Using 911 dispatch data from the Chicago Police Department (CPD), we construct two measures of police response: the time from a 911 call to when a 911 dispatcher finds an available police officer for dispatch (call-to-dispatch) and the time from the 911 call to when the officer arrives on scene (call-to-on-scene). Using a staggered difference-in-differences framework, we find that both response times are significantly increased following the implementation of ShotSpotter by approximately one minute (23\%) and two minutes (15\%) respectively when controlling for the amount of police working and 911 call volumes. These estimates are robust to a variety of sensitivity tests and estimators.

Moreover, we find that the increases in response times are driven by resource-constrained periods. In particular, days where there are less officers on duty or more 911 call volumes each show larger effect sizes, thereby suggesting that ShotSpotter hinders police officers' capacity to complete their other duties in favor of responding to ShotSpotter alerts. Consistent with this mechanism, response times from other time sensitive calls (Priority 2) are also increased while conversely, time-insensitive calls (Priority 3) appear unaffected. 

Consequently, these increased response times come at a significant cost. 
In Section \ref{section:arrests}, we analyze the relationship between police response time and the likelihood of an arrest. We find that Priority 1 calls are 8\% less likely to have the perpetrator caught, consistent with previous literature that attributes faster rapid response to higher clearance rates \citep{blanes_i_vidal_effect_2018} and lower likelihood of injury  \citep{deangelo_police_2023}. The effect is particularly apparent in calls regarding domestic battery (16\%) and domestic disturbances (15\%)—two situations in which may escalate without quick intervention. However, distinct these previous works, we are able to closely examine a determinant of rapid-response directly, rather than focus solely on its consequences.

Surprisingly, the intensive resources allocated to ShotSpotter appear to be relatively fruitless. In Section \ref{section:arrests}, we find little suggestive evidence that ShotSpotter increases the probability of arrest for 911 reports of gun violence. Furthermore, a tertiary analysis reveals that few ShotSpotter dispatches recover firearms or result in an arrest (PUT IN AMOUNT). This is consistent with previous literature that has found limited evidence that ShotSpotter reduces gun-related homicides or arrests \citep{doucette_impact_2021}. Taken together, ShotSpotter appears to misallocate scarce police resources, resulting in a significant social cost.

Although few studies have examined the effects of ShotSpotter, we contribute to a growing literature on the effects of technology on policing, and in a wider context, the criminal justice system. However, while previous studies have found positive effects in the form of algorithmic bail decisions \citep{kleinberg_human_2018}, body-worn cameras \citep{zamoff_who_2022,ferrazares_monitoring_2023}, electronic monitoring \citep{williams_can_2022}, militarization \citep{harris_peacekeeping_2017,bove_police_2017}, predictive policing \citep{mastrobuoni_crime_2020,jabri_algorithmic_2021, heller_machine_2022}, and traffic cameras \citep{conover_effect_2023}, we conversely find significant costs attributed to a policing technology that is expensive both fiscally and socially.\footnote{Chicago is currently under a 33 million dollar 3-year contract with ShotSpotter.} 

More broadly, this study adds to the claim that cities are under-policed, as put forth in \cite{chalfin_are_2018}. Similar studies have explored the added benefits of additional police presence through crime deterrence \citep{chalfin_are_2018, weisburd_police_2021, mello_more_2019}. Distinct from these works, the unique setting of this paper allows us to explore shocks in the availability of officers due to the operating procedures of ShotSpotter. We find that when police resources are stretched thin, the effectiveness of a police force to respond to crimes and arrest perpetrators is diminished. 

The paper proceeds as follows: Section \ref{section:background} provides background information on dispatching procedures and implementation of ShotSpotter in Chicago, Section \ref{section:data} discusses the data, Section \ref{section:empirical} describes the empirical strategy, Section \ref{section:results} presents the main results, Section \ref{section:hetereogeneity} contains heterogeneity analysis, Section \ref{section:discussion} discusses the implications, and Section \ref{section:conclusion} concludes.