---
title: "The Effect of ShotSpotter Technology on Police Response Times"
subtitle: ""
author: Michael Topper and Toshio Ferrazares^[Department of Economics, University of California Santa Barbara, 2017 North Hall, Santa Barbara, CA (michaeltopper@ucsb.edu).]
date: "Last Updated: `r Sys.Date()`"
output: 
  pdf_document:
    number_sections: true
    extra_dependencies: ["flafter"]
indent: true
header-includes:
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{amsmath}
- \usepackage{bbm} ##for indicator
- \usepackage[english]{babel}
- \usepackage{bm}
- \usepackage{float}
- \usepackage{indentfirst}
- \usepackage[fontsize=12pt]{scrextend}
- \usepackage{graphicx}
- \usepackage[utf8]{inputenc}
- \usepackage{pdfpages}
- \usepackage[round]{natbib}
- \usepackage{setspace}\doublespacing
- \usepackage{subfig}
- \usepackage{placeins}
- \usepackage{rotating}
- \floatplacement{figure}{H}
linkcolor: blue
bibliography: "references.bib"
link-citations: yes
nocite: |
abstract: \singlespacing ShotSpotter is an acoustic gunfire detection technology utilized by police departments in over 150 cities with the intention of rapidly dispatching police officers to violent crime scenes to catch perpetrators and reduce gun violence. Despite its prevalence, little is known about its effectiveness in reducing gun violence (intended consequence) nor its effect on 911 emergency response times (unintended consequence) given its resource-intensive operating procedures. In this paper, we utilize variation in timing from ShotSpotter roll-outs across Chicago police districts from 2016-2022 to estimate the causal effects of ShotSpotter on 911 emergency response times that are designated as Priority 1 (immediate dispatch). Using comprehensive 911 dispatch data from the Chicago Police Department, we find that ShotSpotter leads police officers to be dispatched one-minute slower (23\% increase) and arrive on-scene two-minutes later (14\% increase) while controlling for the police officer availability and overall 911 call quantities. Moreover, these effects are driven by resource-constrained periods, and consequently, reduce police officers' success rate in arresting perpetrators (5\%) when responding to emergency calls. However, we also find that ShotSpotter increases the number of gun-related arrests, thereby indicating success in achieving its primary goal, albeit at a significant cost.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(kableExtra)
library(bookdown)
library(modelsummary)
library(fixest)
library(grid)
library(gridExtra)
library(patchwork)
options(modelsummary_model_labels="model")
```

<center>

**JEL Codes:** 

</center>


\newpage
```{r, child = "paper/introduction.Rmd"}

```

```{r, child = "paper/background.Rmd"}

```

```{r, child = "paper/data.Rmd"}

```

```{r, child = "paper/empirical_strategy.Rmd"}

```

```{r, child = "paper/results.Rmd"}

```

```{r, child = "paper/heterogeneity.Rmd"}

```

```{r, child = "paper/discussion.Rmd"}

```

```{r, child = "paper/conclusion.Rmd"}

```


\newpage

\bibliographystyle{apalike}
\bibliography{references.bib}

\newpage
```{r, child = "paper/figures.Rmd", fig.pos="H"}

```


\newpage

```{r, child = "paper/tables.Rmd", fig.pos = "H"}

```

\newpage

```{=tex}
\appendix
\renewcommand{\thefigure}{A\arabic{figure}} \setcounter{figure}{0}
\renewcommand{\thetable}{A\arabic{table}} \setcounter{table}{0}
\renewcommand{\theequation}{A\arabic{table}} \setcounter{equation}{0}
\setcounter{footnote}{0}
\setcounter{page}{1}
```
```{r, child = "paper/appendix_figures.Rmd", fig.pos = "H"}

```


\newpage
```{r, child = "paper/appendix_tables.Rmd", fig.pos = "H"}

```


